add_rules("mode.debug", "mode.release")
set_languages("c++11")
add_includedirs(path.join(os.scriptdir(), "include"), {public = true})
target("calendar")
    set_kind("static")
    add_files("src/*.cxx")
    add_deps("sxtwl")
